services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: user_db
    ports:
      - "3306:3306" 

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5075:5075"
    depends_on:
      - db
    environment:
      - DATABASE_CONNECTION_STRING=Server=db;Port=3306;Database=user_db;Username=root;Password=pass;
      - ASPNETCORE_URLS=http://+:5075